# Generated by Django 5.1.6 on 2025-03-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesType',
            fields=[
                ('accessories_type', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_num', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('main_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_order', models.DateField()),
                ('note', models.CharField(max_length=50)),
                ('is_done', models.BooleanField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.city'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('phone_num', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.job')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.employee'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('dual_sim', models.BooleanField()),
                ('sd_card', models.BooleanField()),
                ('ram', models.IntegerField()),
                ('display_size', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.brand')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.color')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camera', models.IntegerField()),
                ('back_camera', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.phone')),
            ],
        ),
        migrations.CreateModel(
            name='BranchProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('accessories_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.accessoriestype')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('process_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateTimeField()),
                ('movement_type', models.BooleanField()),
                ('is_done', models.BooleanField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'success'), ('R', 'Rejected'), ('P', 'Pending')], default='p', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branchorder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='TransportedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.producttransaction')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
    ]
