# Generated by Django 5.1.6 on 2025-03-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='display_size',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='main_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='main_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='selling_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
