# Generated by Django 5.1.6 on 2025-04-05 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0002_alter_phone_display_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_app.branch'),
        ),
    ]
