# Generated by Django 5.1.6 on 2025-04-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_alter_branch_manager_id_alter_employee_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='main_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
