# Generated by Django 5.1.6 on 2025-04-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0005_alter_product_main_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='display_size',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='main_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
