# Generated by Django 5.1.6 on 2025-04-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0006_alter_phone_display_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='product_id',
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='camera_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobile_app.camera'),
            preserve_default=False,
        ),
    ]
