# Generated by Django 5.1.6 on 2025-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0011_alter_employee_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')]),
        ),
    ]
