# Generated by Django 5.1.6 on 2025-05-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0012_employee_gender_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer Between Branches'), ('RETURN', 'Return to Supplier'), ('ADJUSTMENT', 'Inventory Adjustment')], max_length=20),
        ),
    ]
