# Generated by Django 5.1.6 on 2025-05-18 04:27

import django.core.validators
import mobile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0013_alter_producttransaction_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(validators=[mobile_app.models.Employee.validate_age]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits (e.g., '9876543210').", regex='^\\d{10}$')]),
        ),
    ]
