# Generated by Django 5.1.6 on 2025-05-18 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0014_alter_employee_birthdate_alter_employee_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchorder',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branchproducts',
            name='quantity',
            field=models.IntegerField(help_text='Quantity must be greater than 0', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_num',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits (e.g., '9876543210').", regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits (e.g., '9876543210').", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Quantity must be greater than 0', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='quantity',
            field=models.IntegerField(help_text='Quantity must be greater than 0', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='quantity',
            field=models.IntegerField(help_text='Quantity must be greater than 0', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
