# Generated by Django 5.1.6 on 2025-05-18 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0015_alter_branchorder_note_alter_branchproducts_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='movement_type',
            field=models.CharField(choices=[('sent', 'sent'), ('retrieved', 'retrieved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='process_id',
            field=models.IntegerField(help_text='Quantity must be greater than 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
