# Generated by Django 5.1.6 on 2025-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0016_alter_producttransaction_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='process_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
