# Generated by Django 5.1.6 on 2025-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0018_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
