# Generated by Django 5.1.6 on 2025-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0019_alter_purchase_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchorder',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
