# Generated by Django 5.1.6 on 2025-05-23 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0020_alter_branchorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproducts',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedproducts',
            name='status',
            field=models.CharField(choices=[('S', 'success'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
