# Generated by Django 5.1.6 on 2025-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0021_requestedproducts_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproducts',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestedproducts',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
