# Generated by Django 5.1.6 on 2025-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0022_requestedproducts_processed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
