# Generated by Django 5.1.6 on 2025-05-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0025_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.IntegerField(help_text='Battery capacity in mAh'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_size',
            field=models.DecimalField(decimal_places=2, help_text='Display size in inches', max_digits=3),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dual_sim',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone', serialize=False, to='mobile_app.product'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(help_text='RAM in GB'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sd_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.IntegerField(help_text='Storage in GB'),
        ),
    ]
