# Generated by Django 5.1.6 on 2025-05-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0027_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='id',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accessory', serialize=False, to='mobile_app.product'),
        ),
    ]
