# Generated by Django 5.1.6 on 2025-05-24 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0028_remove_accessories_id_alter_accessories_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportedproducts',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transported_products', to='mobile_app.producttransaction'),
        ),
    ]
