# Generated by Django 5.1.6 on 2025-05-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0029_alter_transportedproducts_process_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportedproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='transportedproducts',
            name='process_id',
        ),
        migrations.AddField(
            model_name='transportedproducts',
            name='transaction',
            field=models.ForeignKey(db_column='process_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transported_items', to='mobile_app.producttransaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='process_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportedproducts',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='producttransaction',
            table='product_transaction',
        ),
        migrations.AlterModelTable(
            name='transportedproducts',
            table='transported_products',
        ),
    ]
