# Generated by Django 5.1.6 on 2025-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0030_rename_product_id_transportedproducts_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='date_of_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
