# Generated by Django 5.1.6 on 2025-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0031_alter_producttransaction_date_of_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
