# Generated by Django 5.1.6 on 2025-05-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0032_alter_color_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
