# Generated by Django 5.1.6 on 2025-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0033_alter_brand_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportedproducts',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='accessoriestype',
            name='accessories_type',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branchorder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestedproducts',
            name='status',
            field=models.CharField(choices=[('S', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
