# Generated by Django 5.1.6 on 2025-05-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0034_rename_product_transportedproducts_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportedproducts',
            old_name='product_id',
            new_name='product',
        ),
    ]
