# Generated by Django 5.1.6 on 2025-05-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0036_alter_requestedproducts_order_id_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
