# Generated by Django 5.1.6 on 2025-05-28 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0038_alter_employee_id_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits (e.g., '9876543210').", regex='^09\\d{10}$')]),
        ),
    ]
