# Generated by Django 5.1.6 on 2025-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0039_alter_branch_branch_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
