# Generated by Django 5.1.6 on 2025-05-28 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0042_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_num',
            field=models.CharField(default=1, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits (e.g., '10987654321').", regex='^09\\d{11}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits (e.g., '9876543210').", regex='^09\\d{10}$')]),
        ),
    ]
