# Generated by Django 5.1.6 on 2025-05-28 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0043_employee_national_num_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_num',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits (e.g., '10987654321').", regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits (e.g., '9876543210').", regex='^09\\d{8}$')]),
        ),
    ]
