# Generated by Django 5.1.6 on 2025-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0046_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='processor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
